name: NetworkPoints
version: '${version}'

main: com.stephanofer.networkpoints.NetworkPointsPlugin
loader: com.stephanofer.networkpoints.NetworkPointsLoader
api-version: '26.1'
load: POSTWORLD

authors: [stephanofer]
website: https://stephanofer.com
description: Global points economy for HERA Network.

dependencies:
  server:
    NetworkBoosters:
      load: BEFORE
      required: false
      join-classpath: true
    NetworkPlayerSettings:
      load: BEFORE
      required: true
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
